/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Coordinate { 'x' : bigint, 'y' : bigint }
export type Direction = { 'Up' : null } |
  { 'Down' : null } |
  { 'Left' : null } |
  { 'Right' : null };
export interface GameSnapshot {
  'timer' : bigint,
  'food' : Coordinate,
  'worldSize' : Coordinate,
  'snacks' : Array<Coordinate>,
  'snakes' : Array<Snake>,
  'timeRemaining' : bigint,
}
export interface GameState {
  'coinBalance' : bigint,
  'dailyClaimHistory' : Array<string>,
  'upgradeLevels' : bigint,
  'unlockedVehicles' : Array<string>,
}
export interface MultiplayerRoom {
  'lastStateUpdateTimestamp' : { 'Stopped' : null } |
    { 'InProgress' : bigint },
  'isActive' : boolean,
  'currentTime' : bigint,
  'players' : Array<[string, string]>,
  'roomId' : string,
  'worldState' : GameSnapshot,
}
export interface Player {
  'username' : string,
  'score' : bigint,
  'snake' : [] | [Snake],
}
export interface Snake {
  'direction' : Direction,
  'body' : Array<Coordinate>,
  'score' : bigint,
}
export interface UserProfile { 'username' : string, 'gameState' : GameState }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkRoomExists' : ActorMethod<[string], boolean>,
  'createRoom' : ActorMethod<[string], string>,
  'getAllRooms' : ActorMethod<[], Array<[string, MultiplayerRoom]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGameState' : ActorMethod<[], GameState>,
  'getRoomParticipants' : ActorMethod<[string], Array<Player>>,
  'getRoomState' : ActorMethod<[string], [] | [MultiplayerRoom]>,
  'getState' : ActorMethod<[string], GameSnapshot>,
  'getTimeRemaining' : ActorMethod<[string], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinRoom' : ActorMethod<
    [string, string],
    { 'AlreadyJoined' : null } |
      { 'Success' : GameSnapshot } |
      { 'RoomNotFoundOrInactive' : null }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveGameState' : ActorMethod<[GameState], undefined>,
  'toggleTimer' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];