/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GameState = IDL.Record({
  'coinBalance' : IDL.Nat,
  'dailyClaimHistory' : IDL.Vec(IDL.Text),
  'upgradeLevels' : IDL.Nat,
  'unlockedVehicles' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'gameState' : GameState,
});
export const Coordinate = IDL.Record({ 'x' : IDL.Nat, 'y' : IDL.Nat });
export const CoinDrop = IDL.Record({
  'value' : IDL.Nat,
  'timeRemaining' : IDL.Int,
  'position' : Coordinate,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addRandomPointsToRoom' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createRoom' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'onSnakeDeath' : IDL.Func(
      [IDL.Text, IDL.Vec(Coordinate), IDL.Nat],
      [IDL.Vec(CoinDrop)],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GameState = IDL.Record({
    'coinBalance' : IDL.Nat,
    'dailyClaimHistory' : IDL.Vec(IDL.Text),
    'upgradeLevels' : IDL.Nat,
    'unlockedVehicles' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'gameState' : GameState,
  });
  const Coordinate = IDL.Record({ 'x' : IDL.Nat, 'y' : IDL.Nat });
  const CoinDrop = IDL.Record({
    'value' : IDL.Nat,
    'timeRemaining' : IDL.Int,
    'position' : Coordinate,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addRandomPointsToRoom' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createRoom' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'onSnakeDeath' : IDL.Func(
        [IDL.Text, IDL.Vec(Coordinate), IDL.Nat],
        [IDL.Vec(CoinDrop)],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };