/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Player {
    username: string;
    score: bigint;
    snake?: Snake;
}
export interface GameSnapshot {
    timer: bigint;
    food: Coordinate;
    worldSize: Coordinate;
    snacks: Array<Coordinate>;
    snakes: Array<Snake>;
    timeRemaining: bigint;
}
export interface Snake {
    direction: Direction;
    body: Array<Coordinate>;
    score: bigint;
}
export interface MultiplayerRoom {
    lastStateUpdateTimestamp: {
        __kind__: "Stopped";
        Stopped: null;
    } | {
        __kind__: "InProgress";
        InProgress: bigint;
    };
    isActive: boolean;
    currentTime: bigint;
    players: Array<[string, string]>;
    roomId: string;
    worldState: GameSnapshot;
}
export interface Coordinate {
    x: bigint;
    y: bigint;
}
export interface GameState {
    coinBalance: bigint;
    dailyClaimHistory: Array<string>;
    upgradeLevels: bigint;
    unlockedVehicles: Array<string>;
}
export interface UserProfile {
    username: string;
    gameState: GameState;
}
export enum Direction {
    Up = "Up",
    Down = "Down",
    Left = "Left",
    Right = "Right"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkRoomExists(roomId: string): Promise<boolean>;
    createRoom(username: string): Promise<string>;
    getAllRooms(): Promise<Array<[string, MultiplayerRoom]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getGameState(): Promise<GameState>;
    getRoomParticipants(roomId: string): Promise<Array<Player>>;
    getRoomState(roomId: string): Promise<MultiplayerRoom | null>;
    getState(_roomId: string): Promise<GameSnapshot>;
    getTimeRemaining(_roomId: string): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    joinRoom(roomId: string, playerName: string): Promise<{
        __kind__: "AlreadyJoined";
        AlreadyJoined: null;
    } | {
        __kind__: "Success";
        Success: GameSnapshot;
    } | {
        __kind__: "RoomNotFoundOrInactive";
        RoomNotFoundOrInactive: null;
    }>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveGameState(state: GameState): Promise<void>;
    toggleTimer(roomId: string): Promise<boolean>;
}
import type { Coordinate as _Coordinate, Direction as _Direction, GameSnapshot as _GameSnapshot, MultiplayerRoom as _MultiplayerRoom, Player as _Player, Snake as _Snake, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkRoomExists(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkRoomExists(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkRoomExists(arg0);
            return result;
        }
    }
    async createRoom(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createRoom(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRoom(arg0);
            return result;
        }
    }
    async getAllRooms(): Promise<Array<[string, MultiplayerRoom]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRooms();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRooms();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGameState(): Promise<GameState> {
        if (this.processError) {
            try {
                const result = await this.actor.getGameState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGameState();
            return result;
        }
    }
    async getRoomParticipants(arg0: string): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomParticipants(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomParticipants(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoomState(arg0: string): Promise<MultiplayerRoom | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomState(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomState(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getState(arg0: string): Promise<GameSnapshot> {
        if (this.processError) {
            try {
                const result = await this.actor.getState(arg0);
                return from_candid_GameSnapshot_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getState(arg0);
            return from_candid_GameSnapshot_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTimeRemaining(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTimeRemaining(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTimeRemaining(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinRoom(arg0: string, arg1: string): Promise<{
        __kind__: "AlreadyJoined";
        AlreadyJoined: null;
    } | {
        __kind__: "Success";
        Success: GameSnapshot;
    } | {
        __kind__: "RoomNotFoundOrInactive";
        RoomNotFoundOrInactive: null;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.joinRoom(arg0, arg1);
                return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinRoom(arg0, arg1);
            return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveGameState(arg0: GameState): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveGameState(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveGameState(arg0);
            return result;
        }
    }
    async toggleTimer(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleTimer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleTimer(arg0);
            return result;
        }
    }
}
function from_candid_Direction_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Direction): Direction {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_GameSnapshot_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameSnapshot): GameSnapshot {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_MultiplayerRoom_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MultiplayerRoom): MultiplayerRoom {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Player_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Player): Player {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Snake_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Snake): Snake {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Snake]): Snake | null {
    return value.length === 0 ? null : from_candid_Snake_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MultiplayerRoom]): MultiplayerRoom | null {
    return value.length === 0 ? null : from_candid_MultiplayerRoom_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    direction: _Direction;
    body: Array<_Coordinate>;
    score: bigint;
}): {
    direction: Direction;
    body: Array<Coordinate>;
    score: bigint;
} {
    return {
        direction: from_candid_Direction_n13(_uploadFile, _downloadFile, value.direction),
        body: value.body,
        score: value.score
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    score: bigint;
    snake: [] | [_Snake];
}): {
    username: string;
    score: bigint;
    snake?: Snake;
} {
    return {
        username: value.username,
        score: value.score,
        snake: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.snake))
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastStateUpdateTimestamp: {
        Stopped: null;
    } | {
        InProgress: bigint;
    };
    isActive: boolean;
    currentTime: bigint;
    players: Array<[string, string]>;
    roomId: string;
    worldState: _GameSnapshot;
}): {
    lastStateUpdateTimestamp: {
        __kind__: "Stopped";
        Stopped: null;
    } | {
        __kind__: "InProgress";
        InProgress: bigint;
    };
    isActive: boolean;
    currentTime: bigint;
    players: Array<[string, string]>;
    roomId: string;
    worldState: GameSnapshot;
} {
    return {
        lastStateUpdateTimestamp: from_candid_variant_n7(_uploadFile, _downloadFile, value.lastStateUpdateTimestamp),
        isActive: value.isActive,
        currentTime: value.currentTime,
        players: value.players,
        roomId: value.roomId,
        worldState: from_candid_GameSnapshot_n8(_uploadFile, _downloadFile, value.worldState)
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    timer: bigint;
    food: _Coordinate;
    worldSize: _Coordinate;
    snacks: Array<_Coordinate>;
    snakes: Array<_Snake>;
    timeRemaining: bigint;
}): {
    timer: bigint;
    food: Coordinate;
    worldSize: Coordinate;
    snacks: Array<Coordinate>;
    snakes: Array<Snake>;
    timeRemaining: bigint;
} {
    return {
        timer: value.timer,
        food: value.food,
        worldSize: value.worldSize,
        snacks: value.snacks,
        snakes: from_candid_vec_n10(_uploadFile, _downloadFile, value.snakes),
        timeRemaining: value.timeRemaining
    };
}
function from_candid_tuple_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _MultiplayerRoom]): [string, MultiplayerRoom] {
    return [
        value[0],
        from_candid_MultiplayerRoom_n5(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Up: null;
} | {
    Down: null;
} | {
    Left: null;
} | {
    Right: null;
}): Direction {
    return "Up" in value ? Direction.Up : "Down" in value ? Direction.Down : "Left" in value ? Direction.Left : "Right" in value ? Direction.Right : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    AlreadyJoined: null;
} | {
    Success: _GameSnapshot;
} | {
    RoomNotFoundOrInactive: null;
}): {
    __kind__: "AlreadyJoined";
    AlreadyJoined: null;
} | {
    __kind__: "Success";
    Success: GameSnapshot;
} | {
    __kind__: "RoomNotFoundOrInactive";
    RoomNotFoundOrInactive: null;
} {
    return "AlreadyJoined" in value ? {
        __kind__: "AlreadyJoined",
        AlreadyJoined: value.AlreadyJoined
    } : "Success" in value ? {
        __kind__: "Success",
        Success: from_candid_GameSnapshot_n8(_uploadFile, _downloadFile, value.Success)
    } : "RoomNotFoundOrInactive" in value ? {
        __kind__: "RoomNotFoundOrInactive",
        RoomNotFoundOrInactive: value.RoomNotFoundOrInactive
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Stopped: null;
} | {
    InProgress: bigint;
}): {
    __kind__: "Stopped";
    Stopped: null;
} | {
    __kind__: "InProgress";
    InProgress: bigint;
} {
    return "Stopped" in value ? {
        __kind__: "Stopped",
        Stopped: value.Stopped
    } : "InProgress" in value ? {
        __kind__: "InProgress",
        InProgress: value.InProgress
    } : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Snake>): Array<Snake> {
    return value.map((x)=>from_candid_Snake_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Player>): Array<Player> {
    return value.map((x)=>from_candid_Player_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _MultiplayerRoom]>): Array<[string, MultiplayerRoom]> {
    return value.map((x)=>from_candid_tuple_n4(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
